; Algorithm to find sin x

(define (cube x) (* x x x))
(define (abs x)
  (if
    (< x 0)
    (- x )
    x
  )
)

(define (p x)
  (- (* 3 x) (* 4 (cube x)))
)

(define (sine angle)
  (if
    (<= angle 0.1)
    angle
    (p (sine (/ angle 3)))
  )
)

(print (sine 0.5236))

; =========================================

; How many times is the procedure p applied when (sine 12.15) is evaluated?

; 5 times

; =========================================

; What is the order of growth in space and number of steps (as a function of a)
; used by the process generated by the sine procedure when (sine a) is evaluated? 

; Both number of steps and space can be represented by ((log a - log 0.1) / log 3) < n
; Order of growth = O(log a)
